### ISSUE TITLE
gitshow repositories location

### ISSUE THREAD

**Issue by michaelpalumbo** [michaelpalumbo/phd#3]
Hi @dvntsea, 

I've decided that at the start of GitShow, one new repository will be created for each instrument/project (where number of projects === number of participants). Then, as the repo changes hands, a new branch will be created for the new person assigned to the instrument's repo. 

**Question for you:**

Do we host the repos under my account, or dispersion lab? Either way they will need to be public. if in DL's org, we can create a team for the participants and restrict their access to just those repos.

Do you have a preference?

**Comment by dvntsea** [comment]
Hi Michael,

Why not host it within the dispersion lab’s account? It would be nice to make this a focal point to build points of synergy, as a virtual platform for this lab-hosted activity.

Best,

Doug

**Comment by michaelpalumbo** [comment]
Absolutely. I've set up a team to coordinate the project and restrict member access privileges repo to within the project (besides the regular dispersion lab members who should have access to other repos)

https://github.com/dispersionlab/gitshow
